"""
Filters regen-context-by-response.jsonl (or any of the other per-response
JSONL files in this project — they all share the response_id/gen_model key)
down to a chosen set of gen_model values.

Usage:
  # keep only responses generated by models you can run locally (<10 GB quantized)
  python3 filter_by_model.py \
      --in regen-context-by-response.jsonl \
      --out regen-context-local-models-only.jsonl \
      --models mistral-7B-instruct llama-2-7b-chat llama-2-13b-chat

  # or invert: drop the ones you can't run locally
  python3 filter_by_model.py \
      --in regen-context-by-response.jsonl \
      --out regen-context-local-models-only.jsonl \
      --exclude gpt-4-0613 gpt-3.5-turbo-0613 llama-2-70b-chat
"""
import json
import argparse
from collections import Counter

# Models that fit under 10 GB locally (quantized GGUF), for convenience.
LOCAL_UNDER_10GB = ["mistral-7B-instruct", "llama-2-7b-chat", "llama-2-13b-chat"]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--in", dest="in_path", required=True)
    ap.add_argument("--out", dest="out_path", required=True)
    ap.add_argument("--models", nargs="*", default=None,
                     help="keep only these gen_model values "
                          f"(shortcut: pass 'local10gb' for {LOCAL_UNDER_10GB})")
    ap.add_argument("--exclude", nargs="*", default=None,
                     help="drop these gen_model values (alternative to --models)")
    args = ap.parse_args()

    if args.models == ["local10gb"]:
        keep = set(LOCAL_UNDER_10GB)
    elif args.models:
        keep = set(args.models)
    else:
        keep = None

    drop = set(args.exclude) if args.exclude else set()

    if keep is None and not drop:
        raise SystemExit("pass either --models or --exclude")

    counts_in = Counter()
    counts_out = Counter()
    n_written = 0
    with open(args.in_path, encoding="utf-8") as fin, \
         open(args.out_path, "w", encoding="utf-8") as fout:
        for line in fin:
            d = json.loads(line)
            model = d.get("gen_model")
            counts_in[model] += 1

            if keep is not None and model not in keep:
                continue
            if model in drop:
                continue

            fout.write(line if line.endswith("\n") else line + "\n")
            counts_out[model] += 1
            n_written += 1

    print("input counts by model:", dict(counts_in))
    print("kept counts by model: ", dict(counts_out))
    print(f"written {n_written} records -> {args.out_path}")


if __name__ == "__main__":
    main()
